### ISSUE TITLE
My failed attempt to convert this project from C# to VB.NET

### ISSUE THREAD

**Issue by zhahaman2001** [Gachl/RustRcon#1]
I am using visual studio express 2013, and I have been referencing the DLL and just including that alongside my VB.NET application. Been doing that for months with everything working great, but now its getting to the point where my code is pushing its way into the C# class, I can make small changes here and there in C# to get it to do what I want but it would be 10,000 times easier for me if it was just in vb.net format. 

When I try to convert from c# to VB.NET I get two areas of code (about 1 to 3 lines) that do not convert properly (using automatic conversion tools) and I can not seem to figure out the proper way to convert these sections myself.

Here is the Package class converted into VB.NET there is a simple error on lines 139 to 142  
http://pastebin.com/g9UKJf2q (Package)

There is a very similar error in the Rcon class on lines 44 to 47
http://pastebin.com/rgsntPFr (Rcon)

I do believe that both the Reader and IllegalProtocolException classes covered without a problem, however I can test them until I fix the other errors XD
http://pastebin.com/tBVN4EQJ (Reader)
http://pastebin.com/UgrQRV1K (IllegalProtocolException)

**Comment by Gachl** [comment]
Hi zhahaman2001

**Package 139 - 142**
The function callback() will go through a list of [Actions](https://msdn.microsoft.com/en-us/library/018hxwa8%28v=vs.110%29.aspx?cs-save-lang=1&cs-lang=vb#code-snippet-1) and call them all in their own [Task](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task%28v=vs.110%29.aspx).
I use a bit reduced code in C# which causes this to mess up in the converter (programs do not convert very good). You'd have to find the VB.net equivalent of creating a Task (linked above) and starting the callback in the task and then starting the task in a for each loop around the callback list (tasks are like threads but easier to use).

**Rcon 44 - 47**
This is again using a Task which messes the converter up. If you solved previous issue in the package class you will have no trouble writing this task which starts the reader.

I'd like to mention again, converting code from one language to another is a very old artefact from back when there were 20 flavours of BASIC and makes absolutely no sense any more these days, I'd like to compare it to converting an airplane into a car, you can do it and use a lot of parts but some important parts like the engine work differently so they have to be replaced. Also for business and money earning you will have a better time if you know C#, as VB.net is the entry level language for .net development. So I would like to recommend spending a week or so fiddling around in the C# project, break shit, fix shit, add shit and add new shit and I promise, after a week of C# only, you will know C# good enough so you can actually write your whole app in it (don't actually write it when you already have the VB code but your next project may be C#).

Let me know if the converted lib works after sorting out Tasks in VB.net (I have never used threading in VB.net) and please consider spending a bit time learning C#, it **will** help you in the future!

Regards,
Gachl

**Comment by Gachl** [comment]
No reply in 16 days.
