### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Joykiller** [Gachl/RustRcon#2]
Not sure whats wrong with it, Just wondering if you still managing this git still or discontinued.

**Comment by Gachl** [comment]
Hello Joykiller

The project has been discontinued as it is only compatible with Rust Legacy. It still works on that version but it's not being updated to work with the new version of the game.

You can still use this library to automate RCON on your Legacy server.

Regards,
Gachl

**Comment by Gachl** [comment]
If you need help getting this to run please paste the call stack and the code you used that has led to the error.

**Comment by Joykiller** [comment]
No I'm good thanks I used the source DLL and rewrote for what I needed.
